title: 'EU Mobility'
default_lang: pl
author:
  name: 'Karol Pilarek '
  email: tomaszdg@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: ''
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
