streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': ['user://themes/quarkextended', 'user://themes/quark']
enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
spectre:
  exp: false
  icons: false
custom_logo:
  eu/user/themes/quarkextended/images/logo/logo3x.png:
    name: logo3x.png
    type: image/png
    size: 104167
    path: eu/user/themes/quarkextended/images/logo/logo3x.png
custom_logo_mobile:
  eu/user/themes/quarkextended/images/logo/logo3x.png:
    name: logo3x.png
    type: image/png
    size: 39995
    path: eu/user/themes/quarkextended/images/logo/logo3x.png
